-- Initial schema for ChickenCalculator application
-- This migration creates all tables based on the existing JPA entities

-- Create admin_users table
CREATE TABLE admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'MANAGER',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_at TIMESTAMP,
    password_change_required BOOLEAN NOT NULL DEFAULT FALSE
);

-- Create locations table
CREATE TABLE locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    address VARCHAR(500),
    manager_name VARCHAR(255) NOT NULL,
    manager_email VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_default BOOLEAN NOT NULL DEFAULT FALSE
);

-- Create sales_data table
CREATE TABLE sales_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    total_sales DECIMAL(10,2) NOT NULL,
    portions_soy DECIMAL(10,2) NOT NULL,
    portions_teriyaki DECIMAL(10,2) NOT NULL,
    portions_turmeric DECIMAL(10,2) NOT NULL,
    location_id BIGINT NOT NULL,
    CONSTRAINT fk_sales_data_location FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE CASCADE,
    CONSTRAINT uk_sales_data_date_location UNIQUE (date, location_id)
);

-- Create marination_log table
CREATE TABLE marination_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    soy_suggested DECIMAL(10,2) NOT NULL,
    teriyaki_suggested DECIMAL(10,2) NOT NULL,
    turmeric_suggested DECIMAL(10,2) NOT NULL,
    soy_pans DECIMAL(10,2) NOT NULL,
    teriyaki_pans DECIMAL(10,2) NOT NULL,
    turmeric_pans DECIMAL(10,2) NOT NULL,
    is_end_of_day BOOLEAN NOT NULL DEFAULT FALSE,
    location_id BIGINT NOT NULL,
    CONSTRAINT fk_marination_log_location FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE CASCADE
);

-- Create indexes for performance
CREATE INDEX idx_sales_date ON sales_data(date);
CREATE INDEX idx_sales_location ON sales_data(location_id);
CREATE INDEX idx_sales_date_location ON sales_data(date, location_id);
CREATE INDEX idx_sales_date_range ON sales_data(location_id, date DESC);

CREATE INDEX idx_marination_timestamp ON marination_log(timestamp);
CREATE INDEX idx_marination_location ON marination_log(location_id);

-- Note: Default admin user will be created by AdminService.initializeDefaultAdmin()
-- This ensures proper BCrypt hashing and environment-specific configurations

-- Insert default main location
INSERT INTO locations (name, slug, manager_name, manager_email, status, is_default, created_at, updated_at)
VALUES ('Main Calculator', 'main', 'System Admin', 'admin@yourcompany.com', 'ACTIVE', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);