spring:
  application:
    name: chicken-calculator
  
  # Database configuration - Use H2 if PostgreSQL not available
  datasource:
    url: ${DATABASE_URL:jdbc:h2:file:/app/data/chicken-calculator-db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: ${DATABASE_DRIVER:org.h2.Driver}
    
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: ${DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
    properties:
      hibernate:
        dialect: ${DATABASE_DIALECT:org.hibernate.dialect.H2Dialect}
    
  # H2 Console (disable in production unless explicitly enabled)
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:false}
      settings:
        web-allow-others: false

# Server configuration
server:
  port: ${PORT:8080}
  forward-headers-strategy: native
  
# CORS configuration for production
cors:
  allowed-origins: 
    - ${FRONTEND_URL:http://localhost:3000}
    - ${RAILWAY_STATIC_URL:https://*.railway.app}
    - ${CUSTOM_DOMAIN:https://your-domain.com}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Actuator for health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      
# Logging
logging:
  level:
    com.example.chickencalculator: INFO
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"